# Meta Data for SEO

## Homepage
title = "Cherise Engage Portal"
titleSeparator = "-"
titleAddition = "Documentation for CheriseGlobal Engage Platform"
description = "We aim to solve all User Enquiry about Engage Portal built on top of Zoho Creator to help our users be informed about all the processes"

## Documentation
docsVersion = "0.1"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "engagecherise.netlify.app"
titleHome = "Cherise Engage Platform"

## Twitter Cards
# twitterSite = "@getdoks"
# twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Cherise Engage"
schemaAuthor = "Sayan Basak"
schemaAuthorTwitter = "https://cheriseglobal.com"
schemaAuthorLinkedIn = "https://cheriseglobal.com"
schemaAuthorGitHub = "https://cheriseglobal.com"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://cheriseglobal.com"
schemaLinkedIn = ""
schemaGitHub = "https://cheriseglobal.com"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://cheriseglobal.com/\">Cherise (India) Pvt. Ltd.</a>"

# Feed
copyRight = "Copyright (c) 2020-2021 Cherise (India) Pvt. Ltd."

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Documentation for Cherise (India) Pvt. Ltd. Engage Portal"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/synbsk/Engage-Cherise"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
